### ISSUE TITLE
[Ubuntu 20.04] Using stdio interprete stops. Replace error

### ISSUE THREAD

**Issue by cibersheep** [daad-adventure-writer/NAPS#2]
- Using pygame is ok
- Using stdio gives this error
```
$ python3 ./interprete.py --gui stdio ../AD/COZUMEL/PART1.DDB 

Traceback (most recent call last):
  File "./interprete.py", line 1089, in <module>
    bucle_daad_nuevo()
  File "./interprete.py", line 198, in bucle_daad_nuevo
    valor = ejecuta_proceso (0)
  File "./interprete.py", line 733, in ejecuta_proceso
    valor = ejecuta_pasos (pasos)
  File "./interprete.py", line 656, in ejecuta_pasos
    cambioFlujo = ejecuta_condacto (entrada[numCondacto][0], entrada[numCondacto][1])
  File "./interprete.py", line 608, in ejecuta_condacto
    valor = funcion (*parametros)  # El * saca los parámetros de la lista
  File "/home/cibersheep/Baixades/IF/games/COZUMEL-abandonsocios/COZUMEL/C/NAPS/condactos_daad.py", line 322, in a1_DESC
    gui.imprime_cadena (desc_locs[locno])
  File "/home/cibersheep/Baixades/IF/games/COZUMEL-abandonsocios/COZUMEL/C/NAPS/gui_stdio.py", line 192, in imprime_cadena
    prn (cadena.replace (tabulador, '\t'), end = '')
TypeError: replace() argument 1 must be str, not None
```

**Comment by DjMorgul** [comment]
Fixed in commit https://github.com/daad-adventure-writer/NAPS/commit/7146cc2e5a26a85d6f56e11d7239f76f40d17200

**Comment by cibersheep** [comment]
Ósom. Sénquiu

![imatge](https://user-images.githubusercontent.com/6640041/155892217-2fe08a47-b45f-4d85-ae84-37abbc005ae3.png)
